%% Reads "Data" file and transorms it in independant cells gathered in Cells 
% Data is a direct import of the Excel file generated by Imaris, when exporting
% track results
 
%Time interval: specifies the real time interval between two acquisition,
%to compute speed.

if ~exist('time_interval', 'var')
    %prompt = "Enter time interval between acquisitions (in min)";
    %time_interval=input(prompt);
    time_interval=inputdlg('Enter time interval between acquisitions (in min)','Set Time Interval', [1 20],{'2'});
    time_interval=str2num(time_interval{1});
end


clear Cells i j deb length;
j=1;
i=1;
cell_begin=1;
Cells=[];

if (max(Data(:,8)-1e9+1)>1)
    while i<length(Data) % Decomposition of Data into individual cells

        if (Data(i+1,8)~=Data(i,8) || i==length(Data)-1); % If we change cell, run the following code ...
            if (i==length(Data)-1);
                i=i+1;
            end
            Cells(j).coordinates=Data(cell_begin:i,[1,2,3,7]);
            cells_length=size(Cells(j).coordinates); % Length of cell j
            cells_length=cells_length(1);


            Cells(j).name=Data(i,8)-1e9+1; 
            % Substracts (1e9-1) to cells nuber to have its actual number 
            Cells(j).instant_displacement=Cells(j).coordinates(2:cells_length,[1,2,3,4])-Cells(j).coordinates(1:(cells_length-1),[1,2,3,4]);  
            % Calculation of displacement of each cells between two timepoints 
            % Also calculates time difference (col 4) because time step may not be constant as gaps may be allowed in tracking
            Cells(j).instant_displacement(1:cells_length-1,4)=Cells(j).instant_displacement(1:cells_length-1,4)*time_interval; 
            % Multiplication of the number of steps between two frame by the actual time interval in order to have a time in minutes
            Cells(j).instant_speed=Cells(j).instant_displacement(:,1:3)./[Cells(j).instant_displacement(:,4),Cells(j).instant_displacement(:,4),Cells(j).instant_displacement(:,4)]; 
            % Calculation of the instant speed by dividing instant displacement by the time interval

            cell_begin=i+1;
            j=j+1;
        end
        i=i+1;
    end
else
    Cells(1).coordinates=Data(:,[1,2,3,7]);
    cells_length=size(Cells(1).coordinates); % length of the cell
    cells_length=cells_length(1);
    Cells(1).name=Data(1,8)-1e9+1; 
    % Substracts (1e9-1) to cells nuber to have its actual number 
    Cells(1).instant_displacement=Cells(1).coordinates(2:cells_length,[1,2,3,4])-Cells(1).coordinates(1:(cells_length-1),[1,2,3,4]);  
    % Calculation of displacement of each cells between two timepoints 
    % Also calculates time difference (col 4) because time step may not be constant as gaps may be allowed in tracking
    Cells(1).instant_displacement(1:cells_length-1,4)=Cells(1).instant_displacement(1:cells_length-1,4)*time_interval; 
    % Multiplication of the number of steps between two frame by the actual time interval in order to have a time in minutes
    Cells(1).instant_speed=Cells(1).instant_displacement(:,1:3)./[Cells(1).instant_displacement(:,4),Cells(1).instant_displacement(:,4),Cells(1).instant_displacement(:,4)]; 
    % Calculation of the instant speed by dividing instant displacement by the time interval
    clear i j cell_begin cells_length;
end




clear i j;
